name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Pacotes Corrigidos e Indentados
  path: ^1.9.0
  url_launcher: ^6.2.6
  google_maps_flutter: ^2.6.1 # NOME CORRETO

  # Pacotes da Aplicação
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2

  # Firebase
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.1.0

  # Outras Utilidades
  image_picker: ^1.1.2
  uuid: ^4.4.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/splash.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
  web: false
  fullscreen: true
