// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5kgmqhbTuz8g8vPLMq_7nRRLYh77tcvo',
    appId: '1:1021101303150:web:aa95a66bf7595a2e9bcd7f',
    messagingSenderId: '1021101303150',
    projectId: 'hellofarmer-805c2',
    authDomain: 'hellofarmer-805c2.firebaseapp.com',
    storageBucket: 'hellofarmer-805c2.firebasestorage.app',
    measurementId: 'G-YVQW7QXQ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8e9W9_bjbeUBx0YpggydUBnihKY-23cw',
    appId: '1:1021101303150:android:8e4ba9da5378f59b9bcd7f',
    messagingSenderId: '1021101303150',
    projectId: 'hellofarmer-805c2',
    storageBucket: 'hellofarmer-805c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhDesPMPR7_FUs0WWfUkq4mToZnOXd7to',
    appId: '1:1021101303150:ios:0f70bb873ca24b399bcd7f',
    messagingSenderId: '1021101303150',
    projectId: 'hellofarmer-805c2',
    storageBucket: 'hellofarmer-805c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhDesPMPR7_FUs0WWfUkq4mToZnOXd7to',
    appId: '1:1021101303150:ios:0f70bb873ca24b399bcd7f',
    messagingSenderId: '1021101303150',
    projectId: 'hellofarmer-805c2',
    storageBucket: 'hellofarmer-805c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5kgmqhbTuz8g8vPLMq_7nRRLYh77tcvo',
    appId: '1:1021101303150:web:a7a293d77d4122419bcd7f',
    messagingSenderId: '1021101303150',
    projectId: 'hellofarmer-805c2',
    authDomain: 'hellofarmer-805c2.firebaseapp.com',
    storageBucket: 'hellofarmer-805c2.firebasestorage.app',
    measurementId: 'G-N4DCZC2YK7',
  );
}
